kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-server-base-role-binding
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: api-server-base
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
