apiVersion: v1
kind: Service
metadata:
  name: api-server-base-service
  namespace: kube-system
spec:
  selector:
    app: api-server-base-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
