apiVersion: v1
kind: Service
metadata:
  name: api-server-base
  namespace: api-server-base
spec:
  selector:
    app: api-server-base
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
