apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-server-base-worker
  namespace: kube-system
  labels:
    app: api-server-base-worker
spec:
  selector:
    matchLabels:
      app: api-server-base-worker
  template: 
    metadata:
      labels:
        app: api-server-base-worker
    spec:
      serviceAccountName: api-server-base
      hostPID: true
      containers:
      - name: api-server-base-worker
        image: yogawulala/k8s-api-server-base:latest
        imagePullPolicy: Never #Always
        securityContext:
          privileged: true
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "2"
            memory: "1024M"
        command: ["python"]
        args: ["/main.py"]
        volumeMounts:
          - name: log-dir
            mountPath: /log
          - name: setting-dir
            mountPath: /setting
          - name: program-file
            mountPath: /main.py
          - name: pkg-dir
            mountPath: /pkg
      volumes:
        - name: log-dir
          hostPath:
            type: DirectoryOrCreate
            path: /etc/api-server-base/log
        - name: setting-dir
          hostPath:
            type: Directory
            path: /etc/api-server-base/setting
        - name: program-file
          hostPath:
            type: File
            path: /etc/api-server-base/src/worker/main.py
        - name: pkg-dir
          hostPath:
            type: Directory
            path: /etc/api-server-base/pkg

