version: 1
disable_existing_loggers: no  # 是否覆蓋以前的配置logger
formatters:
    std:
        format: "%(asctime)s %(levelname)s %(pathname)s.%(lineno)d %(message)s"
        datefmt: "%Y/%m/%d %I:%M:%S"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: std
        stream: ext://sys.stdout
    master:
        class: logging.FileHandler
        level: DEBUG
        formatter: std
        filename: ./log/master.log
        mode: w
    worker:
        class: logging.FileHandler
        level: DEBUG
        formatter: std
        filename: ./log/worker.log
        mode: w
loggers:
    master:
        level: DEBUG
        handlers: [console, master]
        propagate: yes
    worker:
        level: DEBUG
        handlers: [console, worker]
        propagate: yes

root:
    level: INFO
    handlers: [console]
